### ISSUE TITLE
Hiding/Showing Windowbuilder toolbars

### ISSUE THREAD

**Issue by MarcelS4** [eclipse/windowbuilder#110]
We needed the capability to hide the Windowbuilder toolbar as our application has its own toolbar that have similar functionality but not the same. Therefore to have both toolbars visible would cause confusion and interference. 

The problem was that there was no way to hide this toolbar from our application without altering the Windowbuilder itself. 

To solve this issue I have added a class called DesignCompositeManager that is used within Windowbuilder to determine whether to hide or show the WB toolbar. 

This is done by creating the DesignCompositeManager object and passing it into the constructor of the DesignerEditor in our application. 

The default for Windowbuilder looks as follows:
![image](https://user-images.githubusercontent.com/92920738/143411663-d7c25a4f-d6d7-490a-9d40-49a78876750b.png)

After setting the toolbar to be hidden it looks as follows:
![image](https://user-images.githubusercontent.com/92920738/143412061-76c4011d-bb0c-4620-bf42-8c475f3288c0.png)

**Comment by vogella** [comment]
Sorry @MarcelS4 for the delay, but the current version of WB crashes my VM at least under Linux.

**Comment by wimjongman** [comment]
Fixed with Pull #144
