### ISSUE TITLE
WB tests fails with references to 32 bit and unsupported platforms

### ISSUE THREAD

**Issue by vogella** [eclipse/windowbuilder#113]
Looks to me that WB still tries to configure the 32 bit platform.

` /**
   * Configures given {@link TestProject} for using RCP.
   */
  public static void configureSWT(TestProject testProject) throws Exception {
    if (EnvironmentUtils.IS_WINDOWS) {
      testProject.addPlugin("org.eclipse.swt.win32.win32.x86");
    } else if (EnvironmentUtils.IS_LINUX) {
      if (EnvironmentUtils.IS_64BIT_OS) {
        testProject.addPlugin("org.eclipse.swt.gtk.linux.x86_64");
      } else {
        testProject.addPlugin("org.eclipse.swt.gtk.linux.x86");
      }
    } else if (EnvironmentUtils.IS_MAC) {
      if (EnvironmentUtils.IS_MAC_COCOA) {
        if (EnvironmentUtils.IS_64BIT_OS) {
          testProject.addPlugin("org.eclipse.swt.cocoa.macosx.x86_64");
        } else {
          testProject.addPlugin("org.eclipse.swt.cocoa.macosx");
        }
      } else {
        testProject.addPlugin("org.eclipse.swt.carbon.macosx");
      }
    } else {
      throw new UnsupportedOperationException("Unsupported platform.");
    }
  }`

**Comment by vogella** [comment]
EnvironmentUtils still contains lots of unsupported platforms.

**Comment by vogella** [comment]
@wimjongman @lcaron do you have a Mac? ProjectUtils#addSWTLibrary contains to a special case for Mac which I cannot test.

**Comment by wimjongman** [comment]
Cool, yes, I have a mac mini laying around for stuff like this.

**Comment by opcoach** [comment]
![windowbuilder113](https://user-images.githubusercontent.com/1716878/144884106-8f1ff3ba-1926-48c2-99a4-270f92a2d1de.jpg)

**Comment by vogella** [comment]
@opcoach IIRC the databinding tab shows if you have a databinding dependency.
