### ISSUE TITLE
Document the release process of WB

### ISSUE THREAD

**Issue by vogella** [eclipse/windowbuilder#125]
AFAIR @wimjongman handled in the past years the release of WB. We should document the process in the source code, so that we can look it up.

IIRC we following is necessary:

1.) a release record: https://projects.eclipse.org/projects/tools.windowbuilder/releases/
2.) Run the release job on Jenkins
3.) Update the Simrel record
4.) Maybe need a release review from the foundation

(wim)
The following is also required after release
* Update marketplace versions
* Increment feature versions
* Update the website https://www.eclipse.org/windowbuilder/download.php

@wimjongman is that sufficient for the release?

**Comment by wimjongman** [comment]
Started a wiki here: https://github.com/eclipse/windowbuilder/wiki/Release-Checklist

**Comment by wimjongman** [comment]
Lars, I have updated the documentation ^^

Can you add documentation there about how to update simrel?

**Comment by wimjongman** [comment]
Update simrel documentation in release page

**Comment by lcaron** [comment]
Very good job, Congratulations Wim !
