### ISSUE TITLE
Close down WB mailing in favor of https://github.com/eclipse/windowbuilder/discussions

### ISSUE THREAD

**Issue by vogella** [eclipse/windowbuilder#140]
I suggest to close down our WB mailing and only use https://github.com/eclipse/windowbuilder/discussions

@wimjongman and @lcaron WDYT?

**Comment by lcaron** [comment]
👍 for me, good idea. It will "force" users to use discussions, and the less channel we have the easier it is.

**Comment by lcaron** [comment]
I propose to close the ML and update the website after the next release (1.9.8).
For closing the ML, does anybody know what is the procedure ?

**Comment by vogella** [comment]
I guess an email to webmaster@eclipse.org with reference to this bug should be sufficient.

**Comment by wimjongman** [comment]
Fixed

**Comment by wimjongman** [comment]
Sorry, this was not fixed. I propose to keep the mailing list since it is a dev-only channel.
