### ISSUE TITLE
Renaming the root object in the Tree view

### ISSUE THREAD

**Issue by MarcelS4** [eclipse/windowbuilder#149]
We require the ability to set the root object name in the tree view, instead of using the fully qualified name.

![image](https://user-images.githubusercontent.com/92920738/150292198-cf8d348d-7a60-444c-910a-8ccd4e1277a7.png)

**Comment by EinzKleinNico** [comment]
![eclipse change element name](https://user-images.githubusercontent.com/89223042/150312811-8dcbf42d-2a1e-412c-b1ac-bfec5a89c5a2.jpg)

1. Choose the element you want to rename.

The "Properties" window/panel should now show up all variables that you can change. 

2. Click into the field next to "Variable" this should be the first row. 

You could also change the name of elements in your source code but it's much more worke and could also bringup new issues.
