### ISSUE TITLE
Design tab not showing properly (Empty panels)

### ISSUE THREAD

**Issue by ItsOnlyKatniss** [eclipse/windowbuilder#153]
When I create a Frame using the WindowBuilder/Swing Designer/JFrame wizard and open the design tab, I do not see the frame in the tab and all of the other panels (Palette, Components, Properties) are empty:
![Screenshot 2022-01-23 195530](https://user-images.githubusercontent.com/45721520/150668713-074c8600-b4ed-4f02-8af9-a5b502f1b58a.png)

The output in eclipsec.exe reports a call to a "terminally deprecated method" in java.lang.System (setSecurityManager) when the design tab is opened (Bottom 4 lines):
![Screenshot 2022-01-23 195648](https://user-images.githubusercontent.com/45721520/150668819-ad465067-793d-4233-97b2-2b17971117be.png)

I am using Eclipse 2021-12 (4.22.0) and WindowBuilder 1.9.7(.202106041225), running under OpenJDK 17.
I have not tried the preview version yet.

**Comment by EinzKleinNico** [comment]
Well I had the same problem. Its because you dont use the curent version of windowbuilder. The curent version is 1.9.8 pre. If you download WB from eclipse website its the second link not the first.

**Comment by lcaron** [comment]
Hi,

WindowBuilder 19.7 is not compatible with Java 16+. You have to use upcoming release (1.9.8) (https://download.eclipse.org/windowbuilder/lastgoodbuild/)

We plan to release officialy 1.9.8 soon.

**Comment by Bart76** [comment]
The "last good build" completely messes up my Eclipse environment. Thanks.
