### ISSUE TITLE
Windowbuilder Basic UI Layouts

### ISSUE THREAD

**Issue by MarcelS4** [eclipse/windowbuilder#166]
We require that certain layouts be hidden within the Windowbuilder Basic UI. The only layouts that should be available for the user to use in the WB Basic UI are: Absolute Layout, Box Layout, Grid Layout and GridBag Layout.

This should be reflected in the Layouts dropdown option of the properties view.

**Comment by wimjongman** [comment]
Closed with https://github.com/eclipse/windowbuilder/pull/182
