### ISSUE TITLE
WB Team Meeting

### ISSUE THREAD

**Issue by wimjongman** [eclipse/windowbuilder#179]
Sorry for the spam @MarcelS4 @vogella @lcaron 

I have set a meeting for Friday 14:00 15:00 CET

Please update the next comment to add topics to the agenda.

Microsoft Teams meeting 
Join on your computer or mobile app 
[Click here to join the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDIxYWU2M2YtMmZhZi00ZGEzLWFiNjctOWVhOGMxZjIwMjRl%40thread.v2/0?context=%7b%22Tid%22%3a%22b0e58deb-57b7-4d39-8efc-562c88e8939b%22%2c%22Oid%22%3a%226013ebcb-abd8-40f8-8436-cdfecbe07e02%22%7d) 
 
[Learn More](https://aka.ms/JoinTeamsMeeting) | [Meeting options](https://teams.microsoft.com/meetingOptions/?organizerId=6013ebcb-abd8-40f8-8436-cdfecbe07e02&tenantId=b0e58deb-57b7-4d39-8efc-562c88e8939b&threadId=19_meeting_MDIxYWU2M2YtMmZhZi00ZGEzLWFiNjctOWVhOGMxZjIwMjRl@thread.v2&messageId=0&language=en-US)

**Comment by wimjongman** [comment]
Agenda:

* Discuss the Github workflow [1]
* ...

[1] https://www.eclipse.org/lists/platform-dev/msg03439.html

**Comment by lcaron** [comment]
Sorry for my absence. We have a deadline for tonight and a blocking bug was found this morning, I have to fix it :(
