### ISSUE TITLE
Start using a target platform in WindowBuilder

### ISSUE THREAD

**Issue by vogella** [eclipse/windowbuilder#187]
We should start using the target platform instead of compiling against the used IDE.

In addition we should reduce the number of copied JAR files in the source repo and use Maven dependencies direct. org.eclipse.wb.core.lib contains lots of copied JAR files.

@mickaelistria can you tell me if the process of using Maven libs directly is already document of projects outside of platform? I assume we have to sign the libs. Is this supported by the latest CBI plug-ins?

**Comment by vogella** [comment]
@wimjongman @lcaron any concerns here?

**Comment by mickaelistria** [comment]
> I assume we have to sign the libs. Is this supported by the latest CBI plug-ins?

Yes, libs would need to be signed (with PGP), this can be achieved with the right Tycho plugin. See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.tychoeclipsebuilder/pom.xml#L41 , this has to be run against p2 repository so it adds PGP signatures to necessary bundles.

**Comment by wimjongman** [comment]
No concerns. I have created a combined p2/mavenrepo in BIRT. 

https://github.com/eclipse/birt/tree/master/build/org.eclipse.birt.target

**Comment by lcaron** [comment]
No concern for me, thank you @wimjongman

**Comment by vogella** [comment]
Done with https://github.com/eclipse/windowbuilder/pull/220. We could now start removing copied libraries and move to Maven dependencies via the target platform.
