### ISSUE TITLE
Allow user to set font/size preferences for the WindowBuilder source editor

### ISSUE THREAD

**Issue by mjmeijer** [eclipse/windowbuilder#22]
I wanted this, but it appears to be an old issue.
https://www.eclipse.org/forums/index.php?t=msg&th=1087610&goto=1768900&

I have forked repo and will see whether I can provide a solution and pull request

**Comment by lcaron** [comment]
Hi Maarten,

I've fixed today a bug, and the next nightly release will use the "Java Font" instead of the Text Font. Is it what you expect ?

**Comment by mjmeijer** [comment]
I want to be able to set it in preferences general appearance

Maarten Meijer
Verstuurd vanaf mijn iPhone

**Comment by lcaron** [comment]
Ok good idea,

Feel free to ask if you need help !

**Comment by mjmeijer** [comment]
Seems to be a duplicate of https://bugs.eclipse.org/bugs/show_bug.cgi?id=526365 and also resolved in commit 5163faebc9aca7d59a35e48246b65981d5064d2a, closing it. Nice trick in resolving it in plugin.xml, didn't know about that one!

**Comment by lcaron** [comment]
I didn't know it before I fixed this bug ;)
