### ISSUE TITLE
Update SwtTests test suite

### ISSUE THREAD

**Issue by vogella** [eclipse/windowbuilder#239]
Similiar to #237 but for the SWTTests.

**Comment by vogella** [comment]
Current status:

![image](https://user-images.githubusercontent.com/139910/168809394-241f123f-15d5-4823-be05-a5e8988a664d.png)

**Comment by vogella** [comment]
After coming PR

![image](https://user-images.githubusercontent.com/139910/168813392-150d4152-d384-419b-8ca0-fd51c631ca5c.png)

**Comment by wimjongman** [comment]
Woot!

**Comment by vogella** [comment]
Yeah, unfortunately Tycho does not like to run these tests yet. This only makes the tests run locally. Help appretiated.
