### ISSUE TITLE
Add Nebula tests fails with NLP

### ISSUE THREAD

**Issue by vogella** [eclipse/windowbuilder#247]
org.eclipse.wb.tests.designer.rcp.nebula contains multiple Nebula tests, lots of them are currently failing if I run the RCPTest suite. I will disable the Nebual test (~35) so that the rest of the tests can be enabled (~1000) but maybe @lcaron would like to have a look.

**Comment by lcaron** [comment]
Hi @vogella 

I'll have a look this week-end,

Laurent

**Comment by vogella** [comment]
org.eclipse.wb.tests.designer.rcp.nebula.NebulaTests can be used to check the failing test. I will update it to JUnit4 and "temporary" remove it from RcpTests suite https://github.com/eclipse/windowbuilder/pull/256

**Comment by vogella** [comment]
Thanks @ptziegler for enabling the tests and using Nebula update site instead of copied classes.
