### ISSUE TITLE
Add tests to Tycho build

### ISSUE THREAD

**Issue by vogella** [eclipse/windowbuilder#285]
Currently only few tests running via the Tycho build. WindowBuilderTests has ~ 6800 and we only run ~100 in the Tycho build.

Simply adding them to the build does not work so we need to investigate this.

cc @wimjongman @howlger help wanted, this would make the contribution process much more reliable.

**Comment by laeubi** [comment]
> Simply adding them to the build does not work

Can you explain what do not work? That might help other helping you enable them :-)

**Comment by vogella** [comment]
To see the failure in action do the following

- [ ] Open the pom.file of org.eclipse.wb.tests
- [ ] Change line 63 to WindowBuilderTests
- [ ] Remove line 64

Or pull in the following change and run the build with mvn clean verify. https://github.com/eclipse/windowbuilder/pull/294

Pllease note that these ~6800 tests were written before Tycho existed and it took @MarcelS4 and myself multiple days to make them run again in the IDE. We still have not yet completely understood them.

**Comment by vogella** [comment]
Lots of class not found errors and org.eclipse.core.runtime.CoreException: Manifest file is not present for C:\Users\vogella\git\windowbuilder\org.eclipse.wb.tests\target\work\data\TestProject
