### ISSUE TITLE
Build fails on Windows with Invalid URI file:${project_loc:target-platform}/mvn/wb-mvn.target: Illegal character in path at index 7: file:/${project_loc:target-platform}/mvn/wb-mvn.target

### ISSUE THREAD

**Issue by vogella** [eclipse/windowbuilder#295]
Running the build on the command line currently fails with the following error message:

[INFO] Scanning for projects...
[INFO] Resolving target definition file:/C:/Users/vogella/git/windowbuilder/org.eclipse.wb.tests/../target-platform/wb.target for environments=[linux/gtk/x86_64, win32/win32/x86_64, macosx/cocoa/x86_64], include source mode=honor, execution environment=StandardEEResolutionHints [executionEnvironment=OSGi profile 'JavaSE-17' { source level: 17, target level: 17}], remote p2 repository options=org.eclipse.tycho.p2.remote.RemoteAgent@14d298d6...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Resolving file:${project_loc:/target-platform}/mvn/wb-mvn.target
[WARNING] Can't resolve ${project_loc:target-platform} target resoloution might be incomplete
[ERROR] Cannot resolve target definition:
[ERROR]   N/A
[ERROR]
[ERROR] Failed to resolve target definition file:/C:/Users/vogella/git/windowbuilder/org.eclipse.wb.tests/../target-platform/wb.target: Invalid URI file:${project_loc:target-platform}/mvn/wb-mvn.target: Illegal character in path at index 7: file:/${project_loc:target-platform}/mvn/wb-mvn.target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by vogella** [comment]
Most likely caused by [#282](https://github.com/eclipse/windowbuilder/pull/282) cc @laeubi @merks

**Comment by vogella** [comment]
Yeah, moving the content back into one target file, allows the build to complete. Do we have  an URL which is supported by Windows and Linux / Mac? I assume @merks has a Mac and current GH validation "only" runs on Ubuntu, we should propertly also include Windows into the GH action.

**Comment by merks** [comment]
It sounds like this:

https://github.com/eclipse-pde/eclipse.pde/issues/121

I'm not sure how it's implemented in Tycho, but perhaps is a similar bug in Tycho.

**Comment by merks** [comment]
I have Windows and virtual boxes for Mac and Linux.

**Comment by vogella** [comment]
> I have Windows and virtual boxes for Mac and Linux.

So I assume you did not test the build with the target platform split change? Or did it work for you on Windows? 

Sorry but I will have to revert the performance optimization for the setup in case this breaks the build from working on Windows. Unless @laeubi will now tell us how to set it up for both platforms. :-)

**Comment by merks** [comment]
Oddly though this looks like it's not resolved the project name itself which is what happened before this was added to the root pom.xml:

![image](https://user-images.githubusercontent.com/208716/174793654-fa0544dd-aa44-4a9b-8fb2-f9c9f2f3d9c6.png)

Is that present for you locally where you are testing?

**Comment by merks** [comment]
You're sure your root pom.xml is not different from master?

**Comment by merks** [comment]
I ask because it just works for me and it's clearly reading the correct two *.target files.

![image](https://user-images.githubusercontent.com/208716/174795401-ec481171-cb35-4622-820e-0bd331fa4267.png)

**Comment by merks** [comment]
Sh** happens. 🥲
