### ISSUE TITLE
 Error resolving version for plugin 'org.apache.maven.plugins:maven-site-plugin

### ISSUE THREAD

**Issue by SeraphDevelper** [eclipse/windowbuilder#3]
Good evening

I have the following error in pom.xml file
Please could you help me.
Thank you

Multiple annotations found at this line:
	- Error resolving version for plugin 'org.apache.maven.plugins:maven-site-plugin' from the repositories [local (/
	 root/.m2/repository), internal (http://)]: Plugin not found in any plugin 
	 repository
	- Project build error: Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:1.1.0 or one of its 
	 dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:1.1.0

**Comment by wimjongman** [comment]
Please be more specific. What are you doing, what logs do you see? All the details. Reopen after you did.
