### ISSUE TITLE
The bundles from the maven dependencies in the target platform are unsigned

### ISSUE THREAD

**Issue by merks** [eclipse/windowbuilder#302]
I generated this report:

https://download.eclipse.org/oomph/archive/reports-extra/windowbuilder/download.eclipse.org/windowbuilder/lastgoodbuild/index.html

It reports that these bundles are unsigned:

![image](https://user-images.githubusercontent.com/208716/175300289-5b6d83a4-97be-421b-b5a4-ec7cb7c04140.png)

These need to be PGP signed.

I'll contribute a PR to update the pom.xml for this purpose.

**Comment by lcaron** [comment]
Good job, thank you Ed !
