### ISSUE TITLE
Layouts in Swing and SWT fail to change or duplicate Layout option in properties view

### ISSUE THREAD

**Issue by MarcelS4** [eclipse/windowbuilder#311]
For Swing when opening the design view, two Layout options are created in the Properties view and setting either of them throws an exception.

For SWT when switching layouts in the properties view causes the design view to switch to the exception view and produces a misconfiguration error.

**Comment by MarcelS4** [comment]
This occurs on the nightly build and Im currently working on a fix for this

**Comment by lcaron** [comment]
Thank you Marcel

**Comment by MarcelS4** [comment]
Closed with #312
