### ISSUE TITLE
What are the plans for a release and a contribution to SimRel 2022-09?

### ISSUE THREAD

**Issue by merks** [eclipse/windowbuilder#313]
I see there is this release record

https://projects.eclipse.org/projects/tools.windowbuilder/releases/1.10.0

But that date is 3 days after the 2022-09 release.

Is there a plan to produce a new update site and contribute it to SimRel for 2022-09?

**Comment by wimjongman** [comment]
There is no plan ATM. But we can certainly make one.

**Comment by wimjongman** [comment]
I see we have solved a lot of issues and only a few pending.

https://github.com/eclipse/windowbuilder/milestone/2

**Comment by merks** [comment]
Yes, it seems quite a bit was done so I imagine it would be useful (for end users) for that to be included.   If you do plan to release, it would be good to change your release record date to be on or before September 14th...

Today is the deadline for RC1 contributions...

**Comment by wimjongman** [comment]
Yes, I can release it today. Can you help me get it into the release train?

**Comment by merks** [comment]
Just let me know the URL and I'll do it for you.  I assume it will appear here:

https://download.eclipse.org/windowbuilder/

I assume it will be 1.10.0 parallel to this one:

https://download.eclipse.org/windowbuilder/1.9.8/

**Comment by wimjongman** [comment]
Correct.

**Comment by wimjongman** [comment]
1.10.0 has been released.

**Website**
https://www.eclipse.org/windowbuilder/download.php

**Update Sites**
https://download.eclipse.org/windowbuilder/
https://download.eclipse.org/windowbuilder/1.10.0/

**Market place**
https://marketplace.eclipse.org/content/windowbuilder
https://marketplace.eclipse.org/content/windowbuilder-nightly-build
