### ISSUE TITLE
Design Panel has no elements in it Mac OS Java se 18 and java se 1.8

### ISSUE THREAD

**Issue by BrennerLittle** [eclipse/windowbuilder#321]
Design Panel has no elements in it Mac OS Java se 18 and java se 1.8
<img width="1026" alt="Screen Shot 2022-09-22 at 12 17 09 PM" src="https://user-images.githubusercontent.com/46569863/191811265-2be00a18-40d0-45b5-8372-7695945b87bb.png">

**Comment by lcaron** [comment]
Can you please provide logs from error log please ?

**Comment by BrennerLittle** [comment]
There are no error logs there is just no items in the palette. It could be a error or it could be user error.

**Comment by BrennerLittle** [comment]
Im changing this to one issue.

**Comment by BrennerLittle** [comment]
Im changing this to one issue.

**Comment by wimjongman** [comment]
> Can you please provide logs from error log please ?

@lcaron, maybe the palette issue is solved by the new GEF that @vogella et al. released recently

**Comment by lcaron** [comment]
Yes maybe, thank you @wimjongman

**Comment by nelo1986** [comment]
Hello, 
I have the same issue. Did you solve it?
