### ISSUE TITLE
Databinding binds to deprecated classes

### ISSUE THREAD

**Issue by col-panic** [eclipse/windowbuilder#323]
The databinding process binds to deprecated classes. It is, for example, the default to import
`import org.eclipse.jface.databinding.swt.WidgetProperties;` which is directly marked deprecated
and requests change to `import org.eclipse.jface.databinding.swt.typed.WidgetProperties;`

Additionally, if one manualy changes to the non-deprecated classes, they are not marked as bound anymore.

**Comment by wimjongman** [comment]
Thanks for reporting, Marco. Can you make a patch?

**Comment by col-panic** [comment]
Not in the near future! I'll check back if I find a slot!

**Comment by vogella** [comment]
These classes are deleted in the next platform release, so fixing this is recommended if you use dB via wb

**Comment by wimjongman** [comment]
Is this a drop-in replacement?

**Comment by wimjongman** [comment]
It looks like it is not much work...

https://github.com/eclipse/windowbuilder/search?q=org.eclipse.jface.databinding.swt

**Comment by col-panic** [comment]
We also got an auto-generated issue in our project https://github.com/elexis/elexis-3-core/issues/477 considering this topic

**Comment by col-panic** [comment]
I'll try to come up with a PR. The tests aren't supposed to be passing, are they? I had to remove `${uitest.vmparams}` at lease for them to start - but then failing.

**Comment by vogella** [comment]
Most tests are currently running fine, which tests are you referring to?

Marco Descher ***@***.***> schrieb am So., 9. Okt. 2022,
15:15:

**Comment by col-panic** [comment]
> Most tests are currently running fine, which tests are you referring to?

If I run `mvn clean verify` without the `-DskipTests` as mentioned in https://github.com/eclipse/windowbuilder/blob/master/CONTRIBUTING.md (i had to remove the `${uitest.vmparams}` for it to even start. Does this work for you? 
I'm on OS X, tried Java 11 and 17, but see lots of NullPointer and failes.

**Comment by wimjongman** [comment]
Skip the local tests. We do the tests when a PR is created, not all tests are executed.
