### ISSUE TITLE
[SWT] Empty Design tab on Mac M1 Pro

### ISSUE THREAD

**Issue by nelo1986** [eclipse/windowbuilder#344]
### Discussed in https://github.com/eclipse/windowbuilder/discussions/340

**Problem**: The Design Tab is empty and It doesn't allow it to work.
**Architecture**: Apple Silicon (aarch64)

**Screenshot of the issue**

<img width="600" alt="iScreen Shoter - 20221024142538271" src="https://user-images.githubusercontent.com/95741746/197525073-e48755c5-313f-4e15-a72d-749f635d42fb.png">

**Eclipse version:** 2022-09 (4.25.0)
**Build id:** 20220908-1902

**WindowBuilder version**

<img width="600" alt="iScreen Shoter - 20221024142312029" src="https://user-images.githubusercontent.com/95741746/197524671-7b6be6d3-273e-4a29-906d-655694be3e92.png">

There are no error messages.

The same tests on Eclipse x86_64 emulated by Rosseta2 work. Details of the Eclipse x86_64 version:

2022-09 (4.25.0)
Build id: 20220908-1902

Screenshot:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/95741746/197525741-d9bb8cd8-f98f-4cff-a817-53fb1fe0110e.png">

The file which I tested is the following: 

[hi.txt](https://github.com/eclipse/windowbuilder/files/9851684/hi.txt)

**Comment by amitin** [comment]
I can't see that the native parts responsible for visual design pane representation are built for aarch64. So in order to get it working natively for aarch64 the code at https://github.com/eclipse/windowbuilder/tree/master/org.eclipse.wb.os.macosx/native/mac must be built for aarch64 and binaries should reside at https://github.com/eclipse/windowbuilder/tree/master/org.eclipse.wb.os.macosx/os/macosx/aarch64 directory

**Comment by wimjongman** [comment]
We don't check-in binaries.

**Comment by wimjongman** [comment]
Yes. I see that we do not build for aarch64. Thanks for finding that.

**Comment by amitin** [comment]
@wimjongman, I built it but I can't test it. I put the binary here https://github.com/amitin/windowbuilder
Please merge, test it and update your pull request if it works.

**Comment by wimjongman** [comment]
Alexander, thanks! I cannot create the pull request for you. You have to do it for Eclipse legal reasons.

**Comment by wimjongman** [comment]
Alexander, just create a PR from your repo with the added binaries.

**Comment by amitin** [comment]
> Alexander, thanks! I cannot create the pull request for you. You have to do it for Eclipse legal reasons.

OK, did it work for M1? If yes, I'll try to merge it into the master branch.

**Comment by wimjongman** [comment]
> > Alexander, thanks! I cannot create the pull request for you. You have to do it for Eclipse legal reasons.
> 
> OK, did it work for M1? If yes, I'll try to merge it into the master branch.

IDK! I do not have access to an ARM mac. Someone else will have to test, but at least we can build a product. I already created a PR. I could do it from your repo.

**Comment by wimjongman** [comment]
No we have to wait for someone to test it. Are you a WB committer?

**Comment by amitin** [comment]
@wimjongman, I'm one of the founders/creators of SWT Designer (which become WindowBuilder later) since 2003. And yes, I'm still a committer. :)

**Comment by wimjongman** [comment]
Hi Alexander. Thanks for rejoining us!! We can certainly use your help because the project has difficulty catching up with the latest Java/Eclipse changes. 

In this case, I suggest merging your changes so that we have a snapshot ready for people with access to an M1. WDYT?

**Comment by amitin** [comment]
OK, I tested and fixed M1 support, it works fine for me now. Additionally, I added M1 support for text baseline alignment.
See the screenshot. I'll merge the pull requests shortly.
<img width="966" alt="wbp_m1" src="https://user-images.githubusercontent.com/1537180/201497822-37f9362a-5c0c-4141-a0f9-f967d43c0288.png">

**Comment by wimjongman** [comment]
Thanks, Alexander!
