### ISSUE TITLE
Parameterized JComboBox breaks Design tab

### ISSUE THREAD

**Issue by davidhwilliams** [eclipse/windowbuilder#352]
When parameterizing JComboBox in the Source tab and switching to the Design tab a warning is thrown that prevents the Design tab from displaying anything. 
Warning: 
```
Invalid source. No constructor binding.
new JComboBox<>(array) is not valid source for component creation, it references not existing constructor.
```

Work around is to take out the parameters in the constructor which then throws an IDE warning.

Example code:
```
// Noncompliant code that breaks the Design tab
String[] array = {"asdf", "jkl"};
JComboBox<String> comboBox = new JComboBox<>(array);

// Compliant code that throws an IDE warning
String[] array = {"asdf", "jkl"};
JComboBox<String> comboBox = new JComboBox(array);
```

Eclipse Version: 2022-09 (4.25.0)
WindowBuilder Version: 1.12.0.202211051224
Java Version: 1.8.0_202

**Comment by chiwakum** [comment]
I can confirm this is also an issue in Eclipse Version 2022-12. IIRC, this has been a long standing bug. Generics have been around for a LOOOOONG time. It would be helpful to support this language feature in WindowBuilder

**Comment by wimjongman** [comment]
Patches are welcome!
