### ISSUE TITLE
Force the WindowBuilder DesignComosite to use the Light theme

### ISSUE THREAD

**Issue by brotenet** [eclipse/windowbuilder#354]
Hello, 

I am trying to figure out a way to "force" DesignComposite composite to always use the Light theme (or better yet, the system theme) regardless to the Eclipse theme selection because the SWT "dark-mode" color defaults in the GEF canvas of WB are never correct in regards to how the SWT UI looks when build for production (using system theme).
Many times the SWT "dark-mode" color defaults in the GEF canvas of WB become so confusing that I result in setting widget colors statically and once I'm done with the SWT Composite design I remove the static colors one by one.

I tried to find a way to do this by poking around in the _org.eclipse.wb.internal.core.editor_.DesignComposite.java class,  but I cannot seem to find a way to "forcibly" set the widget colors defaults to Light or System theme defaults of the GEF canvas.

Do you know if this is actually possible?
If yes, the can you point to me which classes in the WB plugin sources should I be looking so that I can figure out some sort of a solution?
![wbtheme](https://user-images.githubusercontent.com/4510965/211045174-0724d91b-0498-414b-be81-9dfafcacaa6f.png)

**Comment by vogella** [comment]
There is currently work to enable dark styling of GEF, see https://github.com/eclipse/gef-classic/issues/128

It is better to invest into this issue, another issue would be that WB currently uses copies of GEF in its code, we should move WB to latest official GEF instead of using a custom copy.

cc @azoitl
