### ISSUE TITLE
Failing test cases on Linux builds.

### ISSUE THREAD

**Issue by ptziegler** [eclipse/windowbuilder#370]
There are currently ~150 test cases, which are failing on the Linux builds. We should temporarily disable them, until all fixes which are part of #363 have been merged.

**Comment by vogella** [comment]
> until all fixes which are part of https://github.com/eclipse/windowbuilder/pull/363 have been merged.

Will this fix the tests as well? I though 363 is only about the correct upload of the test results? Sorry for not having a lot of time to investigate the issues, I'm flipping between multiple repos and build jobs today so I might miss things which are clear to you.

**Comment by ptziegler** [comment]
That was the initial plan. But I've "misused" it to keep track and repair all failing test cases, which is why it currently contains 10 commits, instead of just 1.

I think I'll do the following:
- preserve the current state of the branch and roll back anything unrelated to the yaml script
- temporarily disable the failing test cases
- adapt the existing pull-request to also reactivate the tests they repair
- create pull requests for the remaining test cases

**Comment by ptziegler** [comment]
Sounds good to me.

**Comment by ptziegler** [comment]
The last failing test case has been fixed with 37ee1e3b6d55a1634ccdcae28a14cbac81d1b6d2.
With the exception of some sporadic errors, all tests should be green, on both Windows and Linux.
