### ISSUE TITLE
Modify the user tempalete

### ISSUE THREAD

**Issue by Nashnas** [eclipse/windowbuilder#4]
you can format the software like visual studio

**Comment by wimjongman** [comment]
I have no idea what you mean. Please explain clearly and reopen.

**Comment by Nashnas** [comment]
I mean, it's better to have the molding of the objects on the screen to
take place, and wherever you choose, the object is placed at the same point
as the executive program.
در تاریخ ۱۲ اکتبر ۲۰۲۰ ۱:۱۵، "Wim Jongman" <notifications@github.com> نوشت:
