### ISSUE TITLE
Design Tab Has Blank Palette, Structure, and Design Area

### ISSUE THREAD

**Issue by Cullen36** [eclipse/windowbuilder#40]
I've just started to try making applications using windowbuilder, but I have already met a serious problem that makes it impossible.
I have searched for hours online to no avail and tried common fixes for other similar issues - none of which have worked. When I follow the steps for making a new Swing or SWT application (both have this issue), the source code is correctly generated and runs but the design tab does not parse anything as I would expect.
**File structure of my project (ok to my knowledge):** 
![image](https://user-images.githubusercontent.com/70865538/116448677-62d13200-a827-11eb-9088-c6ca8088e2cb.png)
The parsing dialogue opens and closes instantly (reparsing does nothing either), and then I get this:
![image](https://user-images.githubusercontent.com/70865538/116447522-13d6cd00-a826-11eb-9e3b-713945f0bc66.png)
I have tried a full clean reinstall of eclipse and windowbuilder which changed nothing.
- **Eclipse version:** 4.19
- **Windowbuilder version:** 1.9.6.pre (tried 1.9.5 too but it kept installing nightly along with it)
- **Other plugins:** none
- **Log file if useful (it goes over my head):** 
[.log](https://github.com/eclipse/windowbuilder/files/6393732/default.log)
Any Help is much appreciated.

**Comment by lcaron** [comment]
Hi

Thanks to the content of the log, I think that you're using JDK 16. We have an issue with a library used by WindowBuilder, and we're working on it (tough work).

Can you try to add the JVM parameter " --illegal-access=permit" in your Eclipse Configuration ?

Please keep us informed.

Laurent

**Comment by Cullen36** [comment]
Adding that parameter to the config file for Eclipse fixed the problem flawlessly!!
Excellent work, and good luck on fixing that library issue.
Your work is much appreciated!

**Comment by lcaron** [comment]
Thank you for your kind message and your support ;)

**Comment by ABongoCat** [comment]
> Hi
> 
> Thanks to the content of the log, I think that you're using JDK 16. We have an issue with a library used by WindowBuilder, and we're working on it (tough work).
> 
> Can you try to add the JVM parameter " --illegal-access=permit" in your Eclipse Configuration ?
> 
> Please keep us informed.
> 
> Laurent

Hello, I am very very new to Eclipse IDE. Could you tell me pls how to do that?
"Can you try to add the JVM parameter " --illegal-access=permit" in your Eclipse Configuration ?"

**Comment by ABongoCat** [comment]
So just copy that script and save that as a bat file on Windows? Because I see the word Linux there in the script.

**Comment by lcaron** [comment]
No, here is an example (we suppose that JDK 17 is installed in the directory `C:\Program Files\Java\jdk-17` and Eclipse in the directory `C;\Eclipse`)

Save these lines as a batch file :

```
"C:\Program Files\Java\jdk-17\bin\java" -jar c:\eclipse\plugins\org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar
-noverify
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Xms256m
-Xmx2048m
--add-modules=ALL-SYSTEM
--add-opens java.base/java.lang=ALL-UNNAMED
-showsplash
```

**Comment by ABongoCat** [comment]
Ok somehow on my Surface, the .bat can run and all. But there is still an empty Design Tab.

**Comment by cleggink** [comment]
None of this worked for my situation. I've got a Windows 10 machine with jdk-17 and eclipse Version: 2021-12 (4.22). I've added everything to the Eclipse.ini and created the bat file to load Eclipse as shown above and my swing designer palette is still empty with that pesky event loop exception still pooping up. Any ideas would be wonderful.

**Comment by lcaron** [comment]
Hi

If you use JDK 17 adding parameters will be useless.

Can you please try with the upcoming release of WB (https://download.eclipse.org/windowbuilder/lastgoodbuild/) ?

Laurent
