### ISSUE TITLE
Windowbuilder 1.12 does not install in older Eclipse

### ISSUE THREAD

**Issue by wimjongman** [eclipse/windowbuilder#436]
The latest build (1.12) only installs in the IBuild Eclipse. It does not install in the current eclipse or any previous versions because of missing objectweb.asm 9.5.0.

Cannot complete the install because one or more required items could not be found.
  Software being installed: WindowBuilder Java Core 1.12.0.202305121939 (org.eclipse.wb.core.java.feature.feature.group 1.12.0.202305121939)
  Missing requirement: WindowBuilder Core 1.12.0.202305121939 (org.eclipse.wb.core 1.12.0.202305121939) requires 'osgi.bundle; org.objectweb.asm 9.5.0' but it could not be found
  Cannot satisfy dependency:
    From: WindowBuilder Core for Java GUI's 1.9.2.202305121939 (org.eclipse.wb.core.java 1.9.2.202305121939)
    To: osgi.bundle; org.eclipse.wb.core 1.12.0
  Cannot satisfy dependency:
    From: WindowBuilder Java Core 1.12.0.202305121939 (org.eclipse.wb.core.java.feature.feature.group 1.12.0.202305121939)
    To: org.eclipse.equinox.p2.iu; org.eclipse.wb.core.java [1.9.2.202305121939,1.9.2.202305121939]

**Comment by wimjongman** [comment]
It is fine if 1.12 does not install in older Eclipses, but we need to adjust the marketplace entries accordingly.

**Comment by merks** [comment]
Is than an issue of "too strict a lower bound"?   Or should that IU be in the repository?

**Comment by ptziegler** [comment]
> Is than an issue of "too strict a lower bound"? Or should that IU be in the repository?

The lower bound is exactly the issue. WindowBuilder requiires ASM 9.5, but the Eclipse 4.27 is using ASM 9.4. But in principle, any 9.x version should be compatible.

So we could either adjust the lower bounds in the Manifest files or include ASM in the update site.

**Comment by wimjongman** [comment]
I suggest downgrading the asm requirement to 9.0 if that meets our needs. Do we now require Java 17? If so, do we then have a lower limit to 2023-03?

**Comment by merks** [comment]
Anything that runs on Java 11 should also run on Java 17, so I'm not sure that requiring Java 17 has any impact.  If the user isn't running the old IDE with Java 17, the install attempt should warn them.  The EPP packages have been shipped with Java 17 pre-installed for quite some time now...

**Comment by wimjongman** [comment]
Yes, ok. I was looking for the lower limit in the marketplace client, but I will leave it as it is then.
