### ISSUE TITLE
Reflective access with CGLIB breaks windowbuilder in java 16 and higher

### ISSUE THREAD

**Issue by wimjongman** [eclipse/windowbuilder#45]
Hi,
I receive an 'Unhandled event loop exception' exception (see attached) only when Eclipse runs JDK16.
When I use JDK16 for my workspace it works.

I use Eclipse 4.19 with JDK16 patches.

[stack2.txt](https://github.com/eclipse/windowbuilder/files/6599755/stack2.txt)

**Comment by wimjongman** [comment]
It works well when I use " --illegal-access=permit" (in eclipse.ini) as proposed by Laurent.

**Comment by howlger** [comment]
Lombok fixed the problem (which I guess is the same) as follows:
https://github.com/projectlombok/lombok/pull/2811/commits/7069c7e90377952ae7c9a7dfd6786205dfe7ec5f

**Comment by lcaron** [comment]
Bug fixed in WB 1.9.8

**Comment by cniweb** [comment]
> It works well when I use " --illegal-access=permit" (in eclipse.ini) as proposed by Laurent.

The argument --illegal-access=permit is no longer supported with Java 17.

**Comment by wimjongman** [comment]
I don't think we need that anymore since we switched technologies. @lcaron can you confirm?

**Comment by merks** [comment]
A while back, I added this to make it work with Java 17, but I don't know if that's still needed either:
```
--add-opens=java.base/java.lang=ALL-UNNAMED
```

**Comment by howlger** [comment]
> I don't think we need that anymore since we switched technologies. @lcaron can you confirm?

Yes, in recent versions [`--illegal-access=permit` is not used/required anymore](https://github.com/eclipse/windowbuilder/commit/052cf368a80bdd0659cf98679f9ee8c709d4c8cd#diff-8cee4dfac1ee9c8899db3061a385ebe28cdbea2ebb509e46e1126036101656a0).

See also https://github.com/eclipse/windowbuilder/pull/280 (not yet released)

**Comment by lcaron** [comment]
The trick with `--illegal-access=permit` was necessary with Java 16, but it is no longer supported in Java 17.

Anyway the latest release of WB runs without additionnal VM parameter on Java 16+
