### ISSUE TITLE
WindowBuilder moved without leaving a trace

### ISSUE THREAD

**Issue by rolfth** [eclipse/windowbuilder#46]
Try to use google to find the WindowBuilder repository or issue tracker, all you can find is pages with dead ends:

https://projects.eclipse.org/projects/tools.windowbuilder/developer
https://www.eclipse.org/windowbuilder/
https://marketplace.eclipse.org/content/windowbuilder

This leaves the impression that the project is no longer alive.

**Comment by rolfth** [comment]
All these links are valid, but none of them link to the new github WindowBuilder location. For instance, try raising an issue from these pages (you end up in Bugzilla), or doing a checkout (you endup in git.eclipse.org).

It took me half an hour to find this page, even google was not helpful to find it.

**Comment by wimjongman** [comment]
I changed marketplace with an alternative feed:

https://github.com/eclipse/windowbuilder/commits/master.atom

Let me know if anyone knows a better feed.

**Comment by vogella** [comment]
@rolfth can this issue be closed of is there still somthing to do? Please reopen if there is still something to do.
