### ISSUE TITLE
Migration guide for code coming from ancient WindowBuilder Pro?

### ISSUE THREAD

**Issue by Zastai** [eclipse/windowbuilder#498]
We have an old customer coming back to us.

Almost 20 years ago, we delivered a project which included Swing screens using a set of custom components.
When used in their current environment (Windows Server 2003 x86, JDK 1.7.0_90, Eclipse 3.3.1.1 and WindowBuilder Pro 6.4.1 (2007/08/13)), these design just fine.
However, they are trying to update their environments and go over to 64-bit, which means they also have to upgrade to a current WindowBuilder. This is causing design time problems for large screens. If we "downgrade" the screens to use plain Swing controls, the problem goes away, so it is likely a compatibility issue situated in our own components.

Is there a migration guide that describes things that need to be done differently in order to work with WindowBuilder compared to the ancient Pro version? 

# Issue Description

In WindowBuilder Pro, they have

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/13708975/eb969945-5635-46b9-89b6-62b484424a5e)

The screen is 90 lines high, so 1530 pixels (component/line height is fixed at 17 pixels).
The screen's vertical resolution is 1080 pixels.
All items are visible.

The same screen in the current environment (Windows Server 2019 x64, OpenJDK 17.0.6, Eclipse 2023-03 (4.27.0) and WindowBuilder 1.12.0) is not shown completely:

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/13708975/e939323e-fa6d-486d-99a2-e203acb795cd)

Same size and resolution.
The first partially visible item is at 1055 pixels.
Given that the component height is fixed at 17 pixels, its lower edge should be at 1072 pixels.

If they reduce the vertical resolution to 1024, then the visibility is commensurately reduced:

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/13708975/6b1c4187-db5a-40b2-b128-8898999ebadd)

Note that they claim they already investigated the free WindowBuilder over a decade ago, and saw the same problem at that time, which is mainly why they did not switch. The x86->x64 push is now forcing their hand.

If there is no migration guide, and none of this rings a bell as a known issue, I can attach the source of the screen in question along with our component jar for further investigation.

**Comment by wimjongman** [comment]
Yes, please add all the stuff, as small as possible, that shows us the situation.

**Comment by ptziegler** [comment]
I agree, a small reproducer is greatly appreciated.

Maybe as a general question: Does the problem also show up in the preview or is it only the design page, where the screen is partially shown?
