### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by wimjongman** [eclipse/windowbuilder#51]
We need a new website. A one page website should be enough. Is there someone who can make a nice page for us?

* Introduction
* Videos
* Downloads
* Links to documentation
* Links to build engine
* Links to Github
etc..

The current site is here:

https://git.eclipse.org/c/www.eclipse.org/windowbuilder.git/tree/

**Comment by lcaron** [comment]
Wim, for this website do you think that we should keep the "eclipse website" look and feel ? Or something totally different ?

**Comment by lcaron** [comment]
Nice job, I like it a lot ! It is more modern, and I love the flat icons.
Congratulations (and thank you, of course)

**Comment by wimjongman** [comment]
Thanks, Ed!! That looks just great.

**Comment by vogella** [comment]
Thanks, Ed.

+1 for closing

Laurent CARON ***@***.***> schrieb am Do., 21. Okt. 2021,
22:22:
