### ISSUE TITLE
JDK 17 Empty Desing Tab Solution not working

### ISSUE THREAD

**Issue by ABongoCat** [eclipse/windowbuilder#52]
I will focus the usage of Eclipse IDE with WindowBuilder on my Surface Pro 7.
I am referring to my problems in #40 (and #47). Using the .bat File on the desktop allows me to start Eclipse like it should do. One side effect is, that I can't start Eclipse normally anymore with the standard "Eclipse.exe". The Error:
![image](https://user-images.githubusercontent.com/45139479/136713458-3b7e827d-006a-40dd-ae59-c063176fcd97.png)

The .bat file looks like this (how it was shown to me):
```
"C:\Program Files\Java\jdk-17\bin\java" -jar c:\Users\timng\eclipse\java-2021-09\eclipse\plugins\org.eclipse.equinox.launcher_1.6.300.v20210813-1054.jar
-noverify
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Xms256m
-Xmx2048m
--add-modules=ALL-SYSTEM
--add-opens java.base/java.lang=ALL-UNNAMED
-showsplash

```
This is my current situation:
![image](https://user-images.githubusercontent.com/45139479/136713598-e2314eeb-37f6-481d-96a8-7aff846e8ffa.png)

- Version: 2021-09 (4.21)
- Build id: I20210906-0500
- WindowsBuilder: 1.9.5
- Error Log after Creating jFrame (How do I upload the Error file here in GitHub (.log)

**Comment by ABongoCat** [comment]
Command Prompt opens and instantly closes, with nothing happening.

**Comment by merks** [comment]
FYI, what worked for me is adding this to the end of the eclipse.ini
```
--add-opens=java.base/java.lang=ALL-UNNAMED
```
What does not work for me is adding this without the first `=`
```
--add-opens java.base/java.lang=ALL-UNNAMED
```
Nor this with two lines:
```
--add-opens
java.base/java.lang=ALL-UNNAMED
```
which I would have expected should work because all the documented examples I see are without an `=`.

**Comment by merks** [comment]
Use the installer.  It will make sure that the right -vm option is add in order to use the right version of Java; otherwise you'll get just the default one installed on your system each time.

**Comment by ABongoCat** [comment]
I did 3 times. Installed a new installer from website, updated the installer inside the installer menu, restarted my laptop. All ending with the same issue. Like what?

**Comment by ABongoCat** [comment]
C:\Program Files\Java\jdk-17

**Comment by ABongoCat** [comment]
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)

**Comment by lcaron** [comment]
Do you have a directory called "**org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_16.0.2.v20210721-1149**" in `C:\Users\timng\.p2\pool\plugins` ?

If true, replace the lines
```
-vm
C:/Program Files/Java/jdk-17/bin
```
by

```
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_16.0.2.v20210721-1149/jre/bin
```

And restart Eclipse.

**Comment by ABongoCat** [comment]
There isn't
![image](https://user-images.githubusercontent.com/45139479/137384688-5e6a127d-1358-43e4-b883-9823ef0ddb03.png)
