### ISSUE TITLE
Oomph setup for Window Builder?

### ISSUE THREAD

**Issue by merks** [eclipse/windowbuilder#54]
Are you interested in having a setup to easily create a development environment for your project's developers and contributors?

[![Create Eclipse Development Environment for Window Builder](https://download.eclipse.org/oomph/www/setups/svg/Window_Builder.svg)](https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse/windowbuilder/master/setups/WindowBuilderConfiguration.setup&show=true "Click to open Eclipse-Installer Auto Launch or drag into your running installer")

I originally created these "interim" Oomph setups that I have now moved to your Git repository, so the above link reflects the final functionality.

**Comment by wimjongman** [comment]
Ed, I tried it. The only thing that I changed was the location from c:\users\jongw to c:\apps\eclipse\oomph.

I had the following issues:

1. The git protocol failed
2. After restarting and changing it to https the installer required my GitHub user even though I said "anonymous"

Other than that it worked perfectly.

**Comment by merks** [comment]
The git protocol only works if you've uploaded ssh keys.  I always use that so I haven't tested the others.  I should do that.  Thanks for testing!
