### ISSUE TITLE
Update WB to Java 11

### ISSUE THREAD

**Issue by vogella** [eclipse/windowbuilder#62]
As Eclipse moved to minimum Java 11 a longer time ago, we should also move WB to Java 11 to be able to use Java 11 API.

Any concerns with that?

**Comment by C4J** [comment]
Do I understand that WindowBuilder always uses the JDK which is bundled as part of the Eclipse download and that at the moment even though Eclipse is using the latest version of Java - it's only using JDK 8 compatible API calls ? If I understand correctly (and I probably don't) then this would only effect those people who develop WindowBuilder itself and not developers like myself who just use it for their projects - is my understanding correct ?

**Comment by vogella** [comment]
@C4J yes, that is a correct understanding. Also in theory someone who uses a very old Eclipse which still runs on Java 8 could be affected, as latest WB would not work on this release anymore.

**Comment by C4J** [comment]
I recently found out that Eclipse 2021 12 M3 comes with Java 17. I was hoping to use the arm version of that with Apple M1 mac - but apparently JasperStudio plugin is broken with Java 17 - still works with 16 though. 

What versions of java will WindowBuilder run with ? I recall some previous chats about the reflection api or something like that ?

**Comment by vogella** [comment]
Started this with: https://github.com/eclipse/windowbuilder/pull/100 and https://github.com/eclipse/windowbuilder/pull/99

**Comment by lcaron** [comment]
I confirm that WB runs with JDK 8 to 17 now.
Feel free to contact me for further details

**Comment by C4J** [comment]
﻿I guess my only question for now would be - will it work with the Apple Silicon M1 version of eclipse as well as the intel version. I’ll find out in 2-3 weeks if it arrives as per estimate.

**Comment by vogella** [comment]
@C4J No idea, I don't have access to Silicon M1. But this is also a different topic, so if it does not work, please open a new issue.

**Comment by wimjongman** [comment]
Is this done?
