### ISSUE TITLE
Creating Color Picker Preferences

### ISSUE THREAD

**Issue by MarcelS4** [eclipse/windowbuilder#95]
We require the ability to select which color pickers are available when selecting the foreground/background of a widget. 

Previously all the color pickers were available at all times and there was no easy way to hide them, other than removing them from the WindowBuilder. 
Previously the color chooser (for swing widgets) would display the following Color chooser dialog:
![image](https://user-images.githubusercontent.com/92920738/142982050-89ce1ea7-4a00-4ee2-88f8-47683c6d6feb.png)

I have therefore created a preference page in the WindowBuilder category called "Color Chooser". On this preference page it is now able to select which of the color pickers to include in this dialog.
![image](https://user-images.githubusercontent.com/92920738/142982224-24e3a93e-0155-4867-a3c3-c85d534f3bb1.png)

Along with this I have also added a "Custom Colors" color picker that allows the user to specify any color that may or may not appear on any of the other color pickers. 

![image](https://user-images.githubusercontent.com/92920738/142982420-765fed69-5a1e-4c9c-a546-fb1082f88f52.png)

Another small addition to this Color Chooser dialog is that of the warning on the "System colors" tab. This warning has been added to warn the user of the change that may occur in the selected colors depending current system.
 
![image](https://user-images.githubusercontent.com/92920738/142982645-4d042341-ee17-4337-a845-b710161ab814.png)

Linked to PR #91

**Comment by wimjongman** [comment]
Very nice, brother. Thanks!

**Comment by vogella** [comment]
Thanks @MarcelS4 looks good. I see two tests failing during a full run, but if I also get these errors before this change.

Please merge.
